version: '3'

services: 
  app:
    build: .
    command: npm start
    ports: 
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/usr/app
    networks:
      - backend

  db:
    container_name: 'database-node'
    image: mysql
    command: '--init-file /data/application/init.sql'
    restart: always
    hostname: db
    networks:
      - backend
    ports: 
      - '3308:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo  
    volumes:
      - ./init.sql:/data/application/init.sql
      - mysql-data:/var/lib/mysql

networks:
  backend:
    driver: bridge

volumes:
  mysql-data:
